---
title: "DP_Third_Laboratory"
author:
- Teresa Ricciardi
- Albert Bertran
output: pdf_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load, message=FALSE, warning=FALSE}
library(sdcMicro)
```

```{r}
sdcApp()
```

```{r}
obj$inputdata <- readMicrodata(path="testdata", type="rdf", convertCharToFac=FALSE, drop_all_missings=FALSE)
inputdataB <- obj$inputdata
```

```{r}
inputdata <- varToFactor(obj=inputdataB, var="urbrur")
inputdata <- varToFactor(obj=inputdataB, var="roof")
inputdata <- varToFactor(obj=inputdataB, var="walls")
inputdata <- varToFactor(obj=inputdataB, var="water")
inputdata <- varToFactor(obj=inputdataB, var="electcon")
inputdata <- varToFactor(obj=inputdataB, var="relat")
inputdata <- varToFactor(obj=inputdataB, var="sex")
inputdata <- varToFactor(obj=inputdataB, var="age")
inputdata <- varToFactor(obj=inputdataB, var="hhcivil")
## Set up sdcMicro object
sdcObj <- createSdcObj(dat=inputdata,
	keyVars=c("urbrur","roof","walls","water","electcon","relat","sex","age","hhcivil"), 
	numVars=NULL, 
	weightVar=NULL, 
	hhId=NULL, 
	strataVar=NULL, 
	pramVars=NULL, 
	excludeVars=NULL, 
	seed=0, 
	randomizeRecords=FALSE, 
	alpha=c(1))
```

```{r}
slotNames(sdcObj)

str(sdcObj@risk)

riskBefore <- sdcObj@risk$global$risk

riskBeforeVector <- sdcObj@risk$individual[,"risk"]
```

```{r}
mean(riskBeforeVector)
```

```{r}
sdcObjAfter <- kAnon(sdcObj, importance=c(1,6,3,7,4,8,2,9,5), combs=NULL, k=c(5))
```

```{r}
str(sdcObjAfter@risk)

riskAfter <- sdcObjAfter@risk$global$risk

riskAfterVector <- sdcObjAfter@risk$individual[,"risk"]
```
```{r}
mean(riskAfterVector)
```

```{r}
sdcApp()
```

```{r}
indivRisk3 <- c(0.004975, 0.004975, 0.001664, 0.001110)
```

```{r}
1 - prod(1-indivRisk3)
```
Higher

Check_hhrk_2.3:

```{r}
testdatadf<-as.data.frame(testdata)

#categorical vars must be factors
inputdata <- varToFactor(obj=testdatadf, var=c("urbrur","roof","walls","water","electcon","relat","sex","age","hhcivil"))

#defining the sdcObject
sdcObj <- createSdcObj(
  dat=inputdata,
  keyVars=c("urbrur","roof","walls","water","electcon","relat","sex","age","hhcivil"),
  weightVar=c("sampling_weight"),
  hhId=c("ori_hid"),
)

#obtaining the household risk from the object
hh_rk <- sdcObj@risk$individual[sdcObj@origData$ori_hid==1,"hier_risk"]
cat("The household risk for hh_id=1 is:",hh_rk[1])
```

```{r}
data(francdat)
```

```{r}
sdcApp()
```

```{r}
testdatadf<-as.data.frame(francdat)

#categorical vars must be factors
inputdata <- varToFactor(obj=testdatadf, var=c("Key1","Key2","Key4"))

#defining the sdcObject
sdcObj <- createSdcObj(
  dat=inputdata,
  keyVars=c("Key1","Key2","Key4")
)

sdcObj <- varToFactor(sdcObj, "Key1")
sdcObj <- varToFactor(sdcObj, "Key2")
sdcObj <- varToFactor(sdcObj, "Key4")
```

```{r}
sdcSuda <- suda2(obj = sdcObj)

sdcSuda@risk$suda2$score
```

